USE UNIVER
SELECT AUDITORIUM_TYPENAME,AUDITORIUM_NAME
FROM AUDITORIUM_TYPE,AUDITORIUM
WHERE AUDITORIUM.AUDITORIUM_TYPE=AUDITORIUM_TYPE.AUDITORIUM_TYPE AND AUDITORIUM_TYPE.AUDITORIUM_TYPE IN(SELECT AUDITORIUM_TYPE FROM AUDITORIUM_TYPE
WHERE (AUDITORIUM_TYPENAME LIKE 'Лекционная%'))

SELECT AUDITORIUM_TYPE.AUDITORIUM_TYPE,AUDITORIUM.AUDITORIUM_CAPACITY
FROM AUDITORIUM_TYPE,AUDITORIUM
WHERE AUDITORIUM_CAPACITY=(SELECT TOP(1) AUDITORIUM_CAPACITY FROM AUDITORIUM 
WHERE AUDITORIUM_TYPE.AUDITORIUM_TYPE=AUDITORIUM.AUDITORIUM_TYPE
ORDER BY AUDITORIUM_CAPACITY DESC)


SELECT  PROFESSION.PROFESSION_NAME FROM PROFESSION
WHERE NOT EXISTS (SELECT * FROM PULPIT
WHERE PULPIT.PULPIT_NAME=PROFESSION.PROFESSION_NAME)


