use EXAM

SELECT   CUSTOMERS.COMPANY ,AVG(ORDERS.AMOUNT)[S]
FROM CUSTOMERS,ORDERS
GROUP BY AMOUNT,CUSTOMERS.COMPANY

-------------------------------
SELECT ORDERS.REP[«¿ ¿«€],SALESREPS.NAME
FROM  SALESREPS LEFT  JOIN  ORDERS
ON ORDERS.REP=SALESREPS.REP_OFFICE 
  WHERE ORDERS.REP IS NULL

 ------------------------------

