use EXAM
-------------------------------------------------------------1
SELECT  AVG(PRODUCTS.PRICE)[AVG],OFFICES.REGION
FROM PRODUCTS,OFFICES
WHERE OFFICES.REGION IN('Western')
GROUP BY  REGION

SELECT  AVG(PRODUCTS.PRICE)[AVG],OFFICES.REGION,SALESREPS.NAME
FROM PRODUCTS,OFFICES,SALESREPS
WHERE OFFICES.REGION IN('Western')
GROUP BY  REGION,NAME

-------------------------------------------------------------2
SELECT TOP(3)CUSTOMERS.CREDIT_LIMIT,CUSTOMERS.CUST_NUM
FROM CUSTOMERS,SALESREPS
WHERE CUSTOMERS.CREDIT_LIMIT < 50000 

--NO--(ÍÎ ÒÎËÜÊÎ ÎÄÈÍ ÝÒÎ ÆÅ ÂËÎÆÅÍÍÛÉ)
SELECT TOP(3)CUSTOMERS.CREDIT_LIMIT,CUSTOMERS.CUST_NUM
FROM CUSTOMERS 
WHERE CUSTOMERS.CUST_NUM =
(SELECT CUSTOMERS.CUST_NUM FROM  CUSTOMERS
WHERE CUSTOMERS.CREDIT_LIMIT=CUSTOMERS.CREDIT_LIMIT AND CREDIT_LIMIT<50000
 GROUP BY CUST_NUM,CREDIT_LIMIT)

 -----------------------------------------------------------------------------
SELECT OFFICES.CITY,ORDERS.ORDER_DATE
FROM OFFICES,ORDERS
WHERE ORDER_DATE BETWEEN '01.01.2007' AND '01.01.2008'

SELECT * FROM 
(SELECT CASE WHEN ORDER_DATE BETWEEN '01.01.2007' AND '01.01.2008' THEN'TRUE'
ELSE 'NOPE'
END [DATE]
FROM ORDERS GROUP BY CASE 
 CASE WHEN ORDER_DATE BETWEEN '01.01.2007' AND '01.01.2008' THEN'TRUE'
ELSE 'NOPE'
END)






 
 






