/*бшбеярх ярсдемрю х нжемйс он опедлерс ясад*/
SELECT STUDENT.NAME,PROGRESS.NOTE
FROM STUDENT INNER JOIN PROGRESS
ON STUDENT.IDSTUDENT=PROGRESS.IDSTUDENT
WHERE PROGRESS.SUBJECT LIKE '%ясад%'
 
SELECT STUDENT.NAME,PROGRESS.NOTE
FROM STUDENT INNER JOIN PROGRESS
AND 
