use UNIVER
SELECT 
min(AUDITORIUM_CAPACITY)[Минимальная],
max (AUDITORIUM_CAPACITY)[Максимальная],
COUNT(*)[Все],
sum(AUDITORIUM_CAPACITY)[Суммарная]
FROM AUDITORIUM

--------2---------
SELECT AUDITORIUM_TYPE.AUDITORIUM_TYPENAME [Тип аудитории],
min(AUDITORIUM_CAPACITY) [Минимальная],
max (AUDITORIUM_CAPACITY) [Максимальная],
AVG (AUDITORIUM_CAPACITY) [Средняя],
sum(AUDITORIUM_CAPACITY) [Суммарная],
COUNT(*) [Количество]
FROM AUDITORIUM INNER JOIN AUDITORIUM_TYPE
ON AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE
GROUP BY AUDITORIUM_TYPENAME
-------3----------
SELECT *
FROM(SELECT CASE 
WHEN NOTE between 8 and 9 then '8-9'
WHEN NOTE between 6 and 7 then '6-7'
WHEN NOTE between 4 and 5 then '4-5'
else 'меньше 4'
end [Оценка],count(*)[количество]
FROM PROGRESS group by case
WHEN NOTE between 8 and 9 then '8-9'
WHEN NOTE between 6 and 7 then '6-7'
WHEN NOTE between 4 and 5 then '4-5'
else 'меньше 4'
end) as T
order by Case[Оценка]
when '4-5' then 3
when '6-7' then 2
when '8-9' then 1
when 'меньше 4' then 4
else 0
end
----4----
SELECT FACULTY.FACULTY, GROUPS.PROFESSION, GROUPS.YEAR_FIRST,
round(avg(cast(PROGRESS.NOTE as float(4))),2) as Средняя_оценка
FROM FACULTY inner join GROUPS
ON FACULTY.FACULTY = GROUPS.FACULTY
inner join STUDENT
ON STUDENT.IDGROUP = GROUPS.IDGROUP
inner join PROGRESS
ON PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
WHERE PROGRESS.SUBJECT IN ('СУБД','ОАиП')
GROUP BY FACULTY.FACULTY, GROUPS.PROFESSION, GROUPS.YEAR_FIRST
ORDER BY Средняя_оценка desc
----5----
SELECT FACULTY.FACULTY,GROUPS.PROFESSION,AVG(PROGRESS.NOTE)[Среднее]
FROM FACULTY,GROUPS,PROGRESS
WHERE FACULTY.FACULTY IN('ТОВ') 

GROUP BY ROLLUP(FACULTY.FACULTY,PROFESSION,SUBJECT);

----6----
SELECT FACULTY.FACULTY,GROUPS.PROFESSION,AVG(PROGRESS.NOTE)[Среднее]
FROM FACULTY,GROUPS,PROGRESS
WHERE FACULTY.FACULTY IN('ТОВ') 

GROUP BY CUBE(FACULTY.FACULTY,PROFESSION,SUBJECT);

----7----
SELECT FACULTY.FACULTY,GROUPS.PROFESSION,AVG(PROGRESS.NOTE)[Среднее]
FROM FACULTY,GROUPS,PROGRESS
WHERE FACULTY.FACULTY IN('ТОВ') 
GROUP BY ROLLUP (FACULTY.FACULTY,PROFESSION,SUBJECT)

UNION 

SELECT FACULTY.FACULTY,GROUPS.PROFESSION,AVG(PROGRESS.NOTE)[Среднее]
FROM FACULTY,GROUPS,PROGRESS
WHERE FACULTY.FACULTY IN('ХТиТ') 
GROUP BY ROLLUP (FACULTY.FACULTY,PROFESSION,SUBJECT)

----8----
SELECT FACULTY.FACULTY,GROUPS.PROFESSION,AVG(PROGRESS.NOTE)[Среднее]
FROM FACULTY,GROUPS,PROGRESS
WHERE FACULTY.FACULTY IN('ТОВ') 

GROUP BY ROLLUP (FACULTY.FACULTY,PROFESSION,SUBJECT)
INTERSECT/*выводит одинаковые строки из первого, второго и*/
SELECT FACULTY.FACULTY,GROUPS.PROFESSION,AVG(PROGRESS.NOTE)[Среднее]
FROM FACULTY,GROUPS,PROGRESS
WHERE FACULTY.FACULTY IN('ХТиТ') 

GROUP BY ROLLUP (FACULTY.FACULTY,PROFESSION,SUBJECT)

----9----
SELECT FACULTY.FACULTY,GROUPS.PROFESSION,AVG(PROGRESS.NOTE)[Среднее]
FROM FACULTY,GROUPS,PROGRESS
WHERE FACULTY.FACULTY IN('ТОВ') 

GROUP BY ROLLUP (FACULTY.FACULTY,PROFESSION,SUBJECT)
EXCEPT/*есть в первом ,но отсутсвуют во втором */
SELECT FACULTY.FACULTY,GROUPS.PROFESSION,AVG(PROGRESS.NOTE)[Среднее]
FROM FACULTY,GROUPS,PROGRESS
WHERE FACULTY.FACULTY IN('ХТиТ') 
GROUP BY ROLLUP (FACULTY.FACULTY,PROFESSION,SUBJECT)

----10----
SELECT PROGRESS.NOTE,PROGRESS.SUBJECT,
(SELECT COUNT(*) FROM PROGRESS
WHERE PROGRESS.NOTE=PROGRESS.NOTE
AND PROGRESS.SUBJECT=PROGRESS.SUBJECT)[Количество]
FROM PROGRESS
GROUP BY PROGRESS.NOTE,PROGRESS.SUBJECT
HAVING NOTE IN (8,9)

-----------------MYBASE---------------------
USE DB_Lykova
--1--

select min(Ставка)[Ставка],
max(Ставка)[Ставка],
avg(Ставка)[Ставка],
count(*)
from CREDITS
select OFORMLENN_CREDITS.Название_кредита,AVG(OFORMLENN_CREDITS.Сумма)

from CREDITS inner join OFORMLENN_CREDITS
on CREDITS.Наименование_кредита =OFORMLENN_CREDITS.Название_кредита
group by OFORMLENN_CREDITS.Название_кредита

--4--
SELECT Наименование_кредита,sum(Сумма)Сумма
from CREDITS WHERE Наименование_кредита='ИП'
GROUP BY Наименование_кредита
UNION
SELECT Наименование_кредита,sum(Сумма)Сумма
from CREDITS WHERE Наименование_кредита='Льготный'
GROUP BY Наименование_кредита

--10--
SELECT OFORMLENN_CREDITS.Название_кредита,OFORMLENN_CREDITS.Сумма,
(select COUNT(*)   from OFORMLENN_CREDITS
where OFORMLENN_CREDITS.Название_кредита=OFORMLENN_CREDITS.Название_кредита
AND OFORMLENN_CREDITS.Сумма=OFORMLENN_CREDITS.Сумма) [KOL]
FROM OFORMLENN_CREDITS
group by OFORMLENN_CREDITS.Название_кредита,OFORMLENN_CREDITS.Сумма
HAVING Сумма IN (1728390,5647)

